'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Heart, LayoutDashboard, MapPin, Menu, Minus, Plus, Search, ShoppingBag, Ticket, Users, X, Zap } from 'lucide-react'

const events = [
  { id: 1, title: 'Cosquín Rock 2025', artist: 'Festival de música', category: 'Música', date: '15 FEB', fullDate: 'Sábado 15 de febrero, 2025', place: 'Aeródromo Santa María de Punilla', city: 'Córdoba', price: 65000, color: 'coral', tag: 'Más vendido', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1000&q=80' },
  { id: 2, title: 'Lollapalooza Argentina', artist: 'Música en vivo', category: 'Festivales', date: '21 MAR', fullDate: 'Viernes 21 de marzo, 2025', place: 'Hipódromo de San Isidro', city: 'Buenos Aires', price: 98000, color: 'blue', tag: 'Últimas entradas', image: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1000&q=80' },
  { id: 3, title: 'Mundial de Tango', artist: 'Competencia y gala', category: 'Cultura', date: '14 AGO', fullDate: 'Jueves 14 de agosto, 2025', place: 'Usina del Arte', city: 'Buenos Aires', price: 18000, color: 'yellow', tag: 'Recomendado', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80' },
  { id: 4, title: 'Stand Up: Malena Pichot', artist: 'Humor en vivo', category: 'Teatro', date: '08 MAY', fullDate: 'Jueves 8 de mayo, 2025', place: 'Teatro Gran Rex', city: 'Buenos Aires', price: 22000, color: 'purple', tag: 'Disponible', image: 'https://images.unsplash.com/photo-1503095396549-80718e659734?auto=format&fit=crop&w=1000&q=80' },
  { id: 5, title: 'River Plate vs. Talleres', artist: 'Fútbol argentino', category: 'Deportes', date: '30 JUN', fullDate: 'Lunes 30 de junio, 2025', place: 'Estadio Monumental', city: 'Buenos Aires', price: 42000, color: 'green', tag: 'Disponible', image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1000&q=80' },
  { id: 6, title: 'Bresh Buenos Aires', artist: 'La fiesta más linda', category: 'Fiestas', date: '12 ABR', fullDate: 'Sábado 12 de abril, 2025', place: 'GEBA San Martín', city: 'Buenos Aires', price: 15000, color: 'pink', tag: 'Nuevo', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80' },
]

const formatPrice = (price: number) => `$${price.toLocaleString('es-AR')}`

function EventCard({ event, onSelect, favorite, onFavorite }: { event: typeof events[number], onSelect: () => void, favorite: boolean, onFavorite: () => void }) {
  return <article className="event-card">
    <div className="event-image" onClick={onSelect} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') onSelect() }} role="button" tabIndex={0} aria-label={`Ver ${event.title}`}>
      <img src={event.image} alt="" />
      <span className={`event-tag ${event.color}`}>{event.tag}</span>
      <button className={`heart-button ${favorite ? 'is-favorite' : ''}`} onClick={(e) => { e.stopPropagation(); onFavorite() }} aria-label="Agregar a favoritos"><Heart size={17} fill={favorite ? 'currentColor' : 'none'} /></button>
      <div className="date-block"><strong>{event.date.split(' ')[0]}</strong><span>{event.date.split(' ')[1]}</span></div>
    </div>
    <div className="event-copy"><div><span className="eyebrow">{event.category}</span><h3>{event.title}</h3><p>{event.artist}</p></div><strong className="event-price">Desde {formatPrice(event.price)}</strong></div>
    <div className="event-meta"><span><MapPin size={14} />{event.city}</span><span><CalendarDays size={14} />{event.date}</span></div>
  </article>
}

export default function Page() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('Todos')
  const [selected, setSelected] = useState<typeof events[number] | null>(null)
  const [favorites, setFavorites] = useState<number[]>([])
  const [cart, setCart] = useState<{ event: typeof events[number], quantity: number }[]>([])
  const [cartOpen, setCartOpen] = useState(false)
  const [organizer, setOrganizer] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)

  const filtered = useMemo(() => events.filter(e => (category === 'Todos' || e.category === category) && `${e.title} ${e.artist} ${e.city}`.toLowerCase().includes(query.toLowerCase())), [query, category])
  const total = cart.reduce((sum, item) => sum + item.event.price * item.quantity, 0)
  const service = Math.round(total * .1)

  const addToCart = (event: typeof events[number], quantity = 1) => {
    setCart(current => { const found = current.find(x => x.event.id === event.id); return found ? current.map(x => x.event.id === event.id ? { ...x, quantity: x.quantity + quantity } : x) : [...current, { event, quantity }] })
    setSelected(null); setCartOpen(true)
  }
  const updateQuantity = (id: number, delta: number) => setCart(current => current.map(x => x.event.id === id ? { ...x, quantity: Math.max(1, x.quantity + delta) } : x))

  return <main>
    <header className="site-header"><a className="brand" href="#inicio"><span className="brand-mark"><Ticket size={19} /></span>entrada<span className="brand-dot">.</span></a><nav className={menuOpen ? 'mobile-nav open' : 'mobile-nav'}><a href="#eventos">Descubrir eventos</a><a href="#como-funciona">¿Cómo funciona?</a><button className="organizer-link" onClick={() => { setOrganizer(true); setMenuOpen(false) }}><LayoutDashboard size={16} />Soy organizador</button></nav><div className="header-actions"><button className="text-button">Ingresar</button><button className="cart-button" onClick={() => setCartOpen(true)} aria-label="Abrir carrito"><ShoppingBag size={19} /><span>{cart.reduce((a, x) => a + x.quantity, 0)}</span></button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú"><Menu size={20} /></button></div></header>

    {organizer ? <section className="organizer-view"><div className="organizer-top"><button className="back-button" onClick={() => setOrganizer(false)}>← Volver a eventos</button><span className="status-pill"><span /> Cuenta verificada</span></div><div className="organizer-heading"><div><span className="eyebrow accent">Panel de organizador</span><h1>Buen día, <em>Productora Norte.</em></h1><p>Este es el resumen de tus eventos y ventas.</p></div><button className="primary-button">+ Crear evento</button></div><div className="metric-grid"><div><span>Ingresos generados</span><strong>$ 18.420.500</strong><small className="positive">↑ 12,8% vs. mes anterior</small></div><div><span>Entradas vendidas</span><strong>2.846</strong><small className="positive">↑ 8,2% vs. mes anterior</small></div><div><span>Ocupación promedio</span><strong>78,4%</strong><small>En 6 eventos activos</small></div><div><span>Asistencia total</span><strong>94,2%</strong><small>Promedio histórico</small></div></div><div className="dashboard-panel"><div className="panel-header"><div><span className="eyebrow">Rendimiento</span><h2>Ventas de entradas</h2></div><button className="select-button">Últimos 30 días <ChevronDown size={15} /></button></div><div className="chart"><div className="chart-labels"><span>$1.2M</span><span>$800K</span><span>$400K</span><span>$0</span></div><div className="bars">{[35,48,42,58,52,67,62,76,69,81,77,94].map((v, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${v}%` }} /><small>{['01','03','05','07','09','11','13','15','17','19','21','23'][i]}</small></div>)}</div></div></div></section> : <>
      <section className="hero" id="inicio"><div className="hero-shape shape-one" /><div className="hero-shape shape-two" /><div className="hero-inner"><div className="hero-copy"><span className="hero-kicker"><Zap size={14} fill="currentColor" /> Tu próxima experiencia empieza acá</span><h1>Viví lo que<br /><em>te mueve.</em></h1><p>Encontrá eventos, elegí tu lugar y asegurá tu entrada en un solo lugar.</p><div className="hero-search"><Search size={20} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscá por artista, evento o ciudad..." /><button onClick={() => document.getElementById('eventos')?.scrollIntoView({ behavior: 'smooth' })}>Buscar</button></div><div className="hero-suggestions"><span>Popular:</span><button onClick={() => setQuery('Música')}>Música</button><button onClick={() => setQuery('Buenos Aires')}>Buenos Aires</button><button onClick={() => setQuery('Fútbol')}>Fútbol</button></div></div><div className="hero-note"><span className="note-line" /><div><strong>Más de 2.000 eventos</strong><small>para elegir este año</small></div></div></div></section>
      <section className="content-section" id="eventos"><div className="section-heading"><div><span className="eyebrow accent">Elegí tu próxima salida</span><h2>Eventos que no te<br /><em>vas a querer perder.</em></h2></div><button className="outline-button">Ver todos los eventos <ArrowRight size={17} /></button></div><div className="filter-row"><div className="filter-tabs">{['Todos','Música','Festivales','Cultura','Teatro','Deportes'].map(x => <button className={category === x ? 'active' : ''} onClick={() => setCategory(x)} key={x}>{x}</button>)}</div><button className="filter-button"><CalendarDays size={16} /> Fecha <ChevronDown size={14} /></button><button className="filter-button"><MapPin size={16} /> Ubicación <ChevronDown size={14} /></button></div>{filtered.length ? <div className="events-grid">{filtered.map(e => <EventCard key={e.id} event={e} onSelect={() => setSelected(e)} favorite={favorites.includes(e.id)} onFavorite={() => setFavorites(f => f.includes(e.id) ? f.filter(id => id !== e.id) : [...f, e.id])} />)}</div> : <div className="empty-state"><Search size={26} /><h3>No encontramos eventos</h3><p>Probá con otro artista, ciudad o categoría.</p></div>}</section>
      <section className="trust-strip" id="como-funciona"><div><span className="trust-icon"><Check size={18} /></span><div><strong>Compra segura</strong><small>Tus datos están protegidos</small></div></div><div><span className="trust-icon"><Clock3 size={18} /></span><div><strong>Reserva temporal</strong><small>Tu lugar queda guardado</small></div></div><div><span className="trust-icon"><Users size={18} /></span><div><strong>Soporte humano</strong><small>Estamos para ayudarte</small></div></div><div className="trust-cta"><span>¿Organizás eventos?</span><button onClick={() => setOrganizer(true)}>Conocé Entrada para organizadores <ArrowRight size={16} /></button></div></section>
    </>}

    {selected && <div className="overlay" onClick={() => setSelected(null)}><div className="detail-modal" onClick={e => e.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)}><X size={20} /></button><img src={selected.image} alt="" /><div className="detail-body"><span className="eyebrow accent">{selected.category}</span><h2>{selected.title}</h2><p className="detail-artist">{selected.artist}</p><div className="detail-info"><span><CalendarDays size={17} /><b>{selected.fullDate}</b></span><span><MapPin size={17} /><b>{selected.place}</b><small>{selected.city}</small></span></div><div className="availability"><div><span>Campo general</span><strong>Disponible</strong></div><div className="availability-bar"><i style={{ width: '68%' }} /></div><small>Quedan más de 500 entradas</small></div><div className="detail-bottom"><div><small>Desde</small><strong>{formatPrice(selected.price)}</strong><span> + cargos de servicio</span></div><button className="primary-button" onClick={() => addToCart(selected)}>Elegir entradas <ArrowRight size={17} /></button></div></div></div></div>}
    {cartOpen && <div className="overlay cart-overlay" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={e => e.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow accent">Tu selección</span><h2>Carrito <span>({cart.reduce((a, x) => a + x.quantity, 0)})</span></h2></div><button className="close-button" onClick={() => setCartOpen(false)}><X size={20} /></button></div>{cart.length ? <><div className="reserve-note"><Clock3 size={17} /><span>Tu selección está reservada por <strong>09:42</strong> minutos</span></div><div className="cart-items">{cart.map(item => <div className="cart-item" key={item.event.id}><div className={`mini-date ${item.event.color}`}><b>{item.event.date.split(' ')[0]}</b><small>{item.event.date.split(' ')[1]}</small></div><div className="cart-item-copy"><strong>{item.event.title}</strong><small>Entrada general · {item.event.city}</small><div className="quantity"><button onClick={() => updateQuantity(item.event.id, -1)}><Minus size={13} /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.event.id, 1)}><Plus size={13} /></button></div></div><strong className="item-price">{formatPrice(item.event.price * item.quantity)}</strong></div>)}</div><div className="checkout-summary"><div><span>Subtotal</span><strong>{formatPrice(total)}</strong></div><div><span>Cargos de servicio (10%)</span><strong>{formatPrice(service)}</strong></div><div className="summary-total"><span>Total</span><strong>{formatPrice(total + service)}</strong></div><button className="primary-button full" onClick={() => alert('Checkout simulado: tus entradas están listas para continuar.')}>Continuar al pago <ArrowRight size={17} /></button><small className="secure-copy"><Check size={13} /> Pago seguro y protegido</small></div></> : <div className="empty-cart"><ShoppingBag size={28} /><h3>Tu carrito está vacío</h3><p>Elegí un evento y empezá a armar tu próxima experiencia.</p><button className="outline-button" onClick={() => setCartOpen(false)}>Descubrir eventos</button></div>}</aside></div>}
  </main>
}
